name: Submit a Resource!
description: Codeless contribution made easy!
labels:
  - submit-resource
title: 
body:
  - type: dropdown
    attributes:
      label: What kind of resource is it?
      multiple: true
      options:
        - Library
        - Tool
        - Framework
        - Asset
        - Tutorial
        - Other (Please fill in the box below)
    validations:
      required: true
  - type: input
    attributes:
      label: If the resource is set to "other", what is it?
  - type: input
    attributes:
      label: Description
      description: This is what will appear whenever you share a link to someone.
    validations:
      required: true
  - type: input
    attributes:
      label: Authors
      description: Please list each author that has contributed, followed by a comma
        for each contributing author. (i.e, without quotes. "yourname, myname")
    validations:
      required: true
  - type: input
    attributes:
      label: Link to your resource
      description: Provide a link to where your resource is located. (i.e.
        https://github.com/yourname/repository)
    validations:
      required: true
  - type: input
    attributes:
      label: Tags
      description: Please list out all of the tags that your library relates to,
        followed by a comma for each tag. (i.e, without quotes. "tagA, tagB")
    validations:
      required: true
  - type: textArea
    attributes:
      label: Post
      description: Please provide an extensive description and or provide images here.
        (Post field supports markdown!)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What versions does your library/tool support?
      description: Helps us know how compatiable your library/tool is with previous versions.
      options:
        - label: GMS2
        - label: LTS
        - label: 2023.1+
        - label: 2024.4+ 
        - label: Latest current runtime version (local packages)
        - label: Latest current runtime version (prefabs)
        - label: New runtime (local packages)
        - label: New runtime (prefabs)
      validations:
        required: true