name: Submit a Resource!
description: Codeless contribution made easy!
labels: ["submissions"]
title: "Submission: "
body:
  - type: dropdown
    attributes:
      label: What kind of resource is this?
      options:
        - Library
        - Tool 
        - Tutorial
        - Asset
        - Script
        - Other (please specify below)
    validations:
      required: true
  - type: input
    attributes:
      label: If other was selected, what is it?
  - type: input
    attributes:
      label: Logo
      description: A permament link to your logo. (If any)
  - type: input
    attributes:
      label: Description
      description: A short description that will appear as an embed and on the website.
    validations:
      required: true
  - type: input
    attributes:
      label: Authors
      description: Please list each author that has contributed, followed by a comma
        for each contributing author. (i.e, without quotes. "yourname, myname")
    validations:
      required: true
  - type: input
    attributes:
      label: Link to your resource
      description: Provide a link to where your resource is located. (i.e.
        https://github.com/yourname/repository)
    validations:
      required: true
  - type: input
    attributes:
      label: Tags
      description: Please list out all of the tags that your library relates to,
        followed by a comma for each tag. (i.e, without quotes. "tagA, tagB")
    validations:
      required: true
  - type: textarea
    attributes:
      label: Post
      description: Please provide an extensive description and or provide images here.
        (Post field supports markdown!)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What versions does your resource support?
      description: Helps us know how compatiable your library/tool is with previous versions.
      options:
        - label: LTS
        - label: 2023.1+
        - label: 2024.2+ 
        - label: Latest current runtime version (local packages)
        - label: Latest current runtime version (prefabs)
        - label: New runtime (local packages)
        - label: New runtime (prefabs)
        - label: I've selected a version per above
          required: true
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What platforms has this been tested on? 
      options:
        - label: Windows
        - label: MacOSX
        - label: Linux
        - label: HTML5/GX.games
        - label: iOS
        - label: Android
        - label: Consoles
        - label: All of the above